name: Deploy and Run Script on Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy script to remote server
        run: |
          cd $GITHUB_WORKSPACE
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no path/to/your/script.sh ${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTE_HOST }}:/path/to/remote/location/

      - name: Run script on remote server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTE_HOST }} "chmod +x /path/to/remote/location/script.sh && /path/to/remote/location/script.sh"
